[build]
    command = "npm run build"  # Use the custom build command from package.json
    publish = "public/2023"

[[redirects]]
    from = "/2023/"
    to = "https://pycon-turborepo.netlify.app/2023"
    status = 200
    force = true

[[redirects]]
    from = "/2024/"
    to = "https://pycon-turborepo.netlify.app"
    status = 200
    force = true

[[redirects]]
    from = "/2024/"
    to = "https://pycon-turborepo.netlify.app"
    status = 200
    force = true