[build]
  command = "npm run build"
  publish = "public"


[[redirects]]
  from = "public/2023/*"
  to = "/2023/:splat"
  status = 200
  force = true

[[redirects]]
  from = "public/2024/*"
  to = "/:splat"
  status = 200
  force = true
