[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/2023/*"
  to = "/2023/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/2024/*"
  to = "/2024/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
