[build]
    command = "npm run build"  # Use the custom build command from package.json
    publish = "public"

[[redirects]]
    from = "/public/2023/.next/"
    to = "/2023/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/public/2024/.next/"
    to = "/2024/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/public/2024/.next/"
    to = "/:splat"
    status = 200
    force = true