
[[redirects]]
    from = "/2023/*"
    to = "pycon-turborepo.netlify.app/2023/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/2024/*"
    to = "pycon-turborepo.netlify.app/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/*"
    to = "pycon-turborepo.netlify.app/:splat"
    status = 200