export const Tabs = [
  { id: 1, title: "Day 1 (9th October)" },
  { id: 2, title: "Day 2 (10th October)" },
  { id: 3, title: "Day 3 (11th October)" },
  { id: 4, title: "Day 4 (12th October)" },
  { id: 5, title: "Day 5 (13th October)" },
];

export const PYCON_DAY1_SCHEDULE = [
  {
    id: 1,
    title: "Tea",
    room: ["pacificHall", "voltaRoom", "videoConferenceRoom"],
    start: "7:00",
    end: "9:00",
  },
  {
    id: 2,
    title: "Registration and Badge Pickup",
    room: ["pacificHall", "voltaRoom", "videoConferenceRoom"],
    start: "9:00",
    end: "11:00",
  },
  {
    id: 3,
    title: "Welcome and PyCon Official Opening Address",
    room: ["pacificHall", "voltaRoom", "videoConferenceRoom"],
    start: "11:00",
    end: "12:00",
    speaker: "",
  },
  {
    id: 4,
    title: "Pulitzer Center Sponsor Talk",
    room: "pacificHall",
    start: "12:00",
    end: "13:00",
    speaker: "Ivan Mukiibi",
  },
  {
    id: 5,
    title: "Open Source Sprint",
    room: "videoConferenceRoom",
    start: "12:00",
    end: "13:00",
    speaker: null,
    tag: "opensource-sprints",
  },
  {
    id: 6,
    title: "Community Summit ",
    room: "voltaRoom",
    start: "12:00",
    end: "13:00",
    speaker: null,
    tag: "community-summit",
  },
  {
    id: 7,
    title: "Lunch Break",
    room: ["pacificHall", "voltaRoom", "videoConferenceRoom"],
    start: "13:00",
    end: "14:00",
    speaker: null,
  },
  {
    id: 8,
    title: "Chaos Africa Sponsor Talk",
    room: "pacificHall",
    start: "14:00",
    end: "15:00",
    speaker: "Brayan Kai",
  },
  {
    id: 9,
    title: "Community Summit ",
    room: "voltaRoom",
    start: "14:00",
    end: "16:00",
    speaker: null,
    tag: "community-summit",
  },
  {
    id: 10,
    title: "Open Source Sprint",
    room: "videoConferenceRoom",
    start: "14:00",
    end: "16:00",
    speaker: null,
    tag: "opensource-sprints",
  },

  {
    id: 11,
    title: "Posit Talk",
    room: "pacificHall",
    start: "15:00",
    end: "16:00",
    speaker: "Hassan Kibirige",
  },
  {
    id: 12,
    title: "Open Source Panel",
    room: ["pacificHall", "voltaRoom", "videoConferenceRoom"],
    start: "16:00",
    end: "17:00",
  },
];

export const PYCON_DAY2_SCHEDULE = [
  {
    id: 1,
    title: "Tea",
    room: ["pacificHall", "voltaRoom", "videoConferenceRoom"],
    start: "7:00",
    end: "8:30",
  },
  {
    id: 102,
    title: "Welcome and Announcements",
    room: "pacificHall",
    start: "8:30",
    end: "9:00",
    speaker: "Kirabo Atuhurira",
  },
  {
    id: 2,
    title: "Diversity Panel",
    room: "pacificHall",
    start: "9:00",
    end: "10:00",
  },
  {
    id: 3,
    title: "Pydata Mini-Conference",
    room: "pacificHall",
    start: "10:00",
    end: "13:00",
    tag: "pydata",
  },
  {
    id: 4,
    title: "Open Source Sprint",
    room: "voltaRoom",
    start: "10:00",
    end: "13:00",
    tag: "opensource-sprints",
  },
  {
    id: 5,
    title: "Open Space: Cracking the Coding Interview",
    room: "videoConferenceRoom",
    start: "10:00",
    end: "13:00",
  },
  {
    id: 6,
    title: "Lunch Break",
    room: ["pacificHall", "voltaRoom", "videoConferenceRoom"],
    start: "13:00",
    end: "14:00",
    speaker: null,
  },
  {
    id: 7,
    title: "Pydata Mini-Conference",
    room: "pacificHall",
    start: "14:00",
    end: "16:00",
    tag: "pydata",
  },
  {
    id: 8,
    title: "Open Source Sprint",
    room: "voltaRoom",
    start: "14:00",
    end: "16:00",
    tag: "opensource-sprints",
  },
  {
    id: 9,
    title: "Open Space: Mental Health and Burn Out",
    room: "videoConferenceRoom",
    start: "14:00",
    end: "16:00",
  },
  {
    id: 10,
    title: "State of the Community Address",
    room: "pacificHall",
    start: "16:00",
    end: "17:00",
    speaker: "Sumaiya Nalukwago",
  },
];

export const PYCON_DAY3_SCHEDULE = [
  {
    id: 101,
    title: "Tea and Registration",
    room: ["voltaRoom", "pacificHall", "videoConferenceRoom"],
    start: "8:00",
    end: "10:00",
    speaker: null,
  },
  {
    id: 2,
    title: "Opening Keynote",
    room: "pacificHall",
    start: "10:00",
    end: "11:00",
    speaker: "Łukasz Langa",
  },
  {
    id: 3,
    title: "AI Agents and the Age of Autonomous Systems",
    room: "pacificHall",
    start: "11:00",
    end: "11:30",
    speaker: "Musiitwa Edmond",
  },
  {
    id: 4,
    title: "Building SMART Recommendation Systems in Python (Using intellikit)",
    room: "voltaRoom",
    start: "11:00",
    end: "11:30",
    speaker: "Arthur Kakande",
  },
  {
    id: 5,
    title: "Serving TensorFlow Models with FastAPI",
    room: "videoConferenceRoom",
    start: "11:00",
    end: "11:30",
    speaker: "Wesley Kambale",
  },
  {
    id: 6,
    title: "Full Stack Python Web Dev? Introducing Reflex",
    room: "pacificHall",
    start: "11:30",
    end: "12:00",
    speaker: "Ssali Jonathan Kiggundu",
  },
  {
    id: 7,
    title:
      "Core Principles: Exploring Asynchronous IO Patterns in Python: Strategies for Enhanced Performance and Scalability",
    room: "pacificHall",
    start: "12:00",
    end: "12:30",
    speaker: "Angufibo Lincoln",
  },
  {
    id: 8,
    title: "Explainable AI with Python",
    room: "voltaRoom",
    start: "12:00",
    end: "12:30",
    speaker: "Brayan Mwanyumba",
  },
  {
    id: 9,
    title:
      "Python with Kafka: Get started on modern stream processing with Python",
    room: "videoConferenceRoom",
    start: "12:00",
    end: "12:30",
    speaker: "Mark Lubega",
  },
  {
    id: 10,
    title: "End-to-end testing with Selenium and Python",
    room: "pacificHall",
    start: "12:30",
    end: "13:00",
    speaker: "Victoria Mutai and Pauline Gechure",
  },
  {
    id: 11,
    title: "Lunch Break",
    room: ["pacificHall", "voltaRoom", "videoConferenceRoom"],
    start: "13:00",
    end: "14:00",
    speaker: null,
  },
  {
    id: 12,
    title: "Official Expo Hall Time",
    room: ["pacificHall", "voltaRoom", "videoConferenceRoom"],
    start: "14:00",
    end: "14:30",
    speaker: null,
  },
  {
    id: 13,
    title:
      "Dive into the world of Explainable AI (XAI) with Python, exploring how to make AI models transparent and understandable, fostering trust and ethical use in AI applications.",
    room: "pacificHall",
    start: "14:30",
    end: "15:00",
    speaker: "Brayan Mwanyumba",
  },
  {
    id: 14,
    title: "Click It & Script It: Automating Your Desktop with PyAutoGUI",
    room: "voltaRoom",
    start: "14:30",
    end: "15:00",
    speaker: "Collins Mesue",
  },
  {
    id: 15,
    title: "Python in Web3: Libraries, Techniques, and Local Dev Challenges",
    room: "pacificHall",
    start: "15:30",
    end: "16:00",
    speaker: "Oliseh Genesis",
  },
  {
    id: 16,
    title:
      "Leveraging Kafka Streams: Real-time Logging and Monitoring for Django Applications",
    room: "voltaRoom",
    start: "15:30",
    end: "16:00",
    speaker: "Okot Daniel",
  },
  {
    id: 17,
    title: "Beginner's Guide to Data Orchestration with Apache Airflow",
    room: "voltaRoom",
    start: "16:00",
    end: "16:30",
    speaker: "Okumu Justine",
  },
  {
    id: 17,
    title: "Beginner's Guide to Data Orchestration with Apache Airflow",
    room: "pacificHall",
    start: "16:00",
    end: "16:30",
    speaker: "Okumu Justine",
  },
  {
    id: 18,
    title: "Closing Keynote",
    room: "pacificHall",
    start: "16:30",
    end: "17:30",
    speaker: "Kelvin Ndemo",
  },
  {
    id: 19,
    title: "Announcements and Closing",
    room: "pacificHall",
    start: "17:30",
    end: "18:00",
    speaker: null,
  },
];

export const PYCON_DAY4_SCHEDULE = [
  {
    id: 1,
    title: "Breakfast and Expo time",
    room: ["pacificHall", "voltaRoom", "videoConferenceRoom"],
    start: "7:00",
    end: "10:00",
  },
  {
    id: 2,
    title: "Keynote",
    room: "pacificHall",
    start: "10:00",
    end: "11:00",
    speaker: "Marlene Mhangami",
  },
  {
    id: 3,
    title: "Deploying Python on Serverless Infrastructure for Free",
    room: "pacificHall",
    start: "11:00",
    end: "11:30",
    speaker: "Kayondo Edward",
  },
  {
    id: 4,
    title: "Guide to Test-Driven Development using PyTest",
    room: "videoConferenceRoom",
    start: "11:00",
    end: "11:30",
    speaker: "Doki Golder Sylivia",
  },
  {
    id: 5,
    title:
      "Exploring Conversational AI: Crafting AI-Powered Django Apps with Gemini",
    room: "pacificHall",
    start: "11:30",
    end: "12:00",
    speaker: "Hassan Bahati",
  },
  {
    id: 6,
    title:
      "From Syntax to Solutions: Mastering Technical Writing for Developers",
    room: "pacificHall",
    start: "12:00",
    end: "12:30",
    speaker: "Fanny Nyayic",
  },
  {
    id: 7,
    title: "API 101 API fundamentals",
    room: "voltaRoom",
    start: "12:00",
    end: "12:30",
    speaker: "Felix Jumason",
  },
  {
    id: 8,
    title: "Chaos Africa Workshop",
    room: "videoConferenceRoom",
    start: "12:00",
    end: "12:30",
    speaker: "Allan Kiche and Brayan Kai Mwanyumba",
  },
  {
    id: 9,
    title: "Revolutioned. Whats New in Python 3.10",
    room: "pacificHall",
    start: "12:30",
    end: "13:00",
    speaker: "Allan Kiche",
  },
  {
    id: 10,
    title: "Lunch Break",
    room: ["pacificHall", "voltaRoom", "videoConferenceRoom"],
    start: "13:00",
    end: "14:00",
    speaker: null,
  },
  {
    id: 11,
    title: "Official Expo Hall Time",
    room: ["pacificHall", "voltaRoom", "videoConferenceRoom"],
    start: "14:00",
    end: "14:30",
    speaker: null,
  },
  {
    id: 12,
    title: "Python for C2 (Command and Control) Operations",
    room: "pacificHall",
    start: "14:30",
    end: "15:00",
    speaker: "Salim Abdella",
  },
  {
    id: 13,
    title: "Crafting Ubiquity: A Model's Odyssey",
    room: "voltaRoom",
    start: "14:30",
    end: "15:00",
    speaker: "Kayongo Johnson Brian",
  },
  {
    id: 14,
    title: "Behind the scences of an Ads Prediction System",
    room: "videoConferenceRoom",
    start: "14:30",
    end: "15:00",
    speaker: "Bunmi Akinremi",
  },
  {
    id: 15,
    title: "Building and Consuming APIs with Python",
    room: "pacificHall",
    start: "15:00",
    end: "15:30",
    speaker: "Felix Jumason",
  },
  {
    id: 16,
    title: "Django Rest Framework with J2J architecture",
    room: "pacificHall",
    start: "15:30",
    end: "16:00",
    speaker: "Tumusiime Ezra",
  },
  {
    id: 17,
    title: "Train & Debug A model with Responsible AI Dashboard",
    room: "voltaRoom",
    start: "15:30",
    end: "16:00",
    speaker: "Anthony Byansi",
  },
  {
    id: 18,
    title: "GitHub Sponsor  Student Workshop",
    room: "videoConferenceRoom",
    start: "15:30",
    end: "16:00",
    speaker: "Allan Kiche and Brayan Kai Mwanyumba",
  },
  {
    id: 19,
    title: "Unlock Python's Potential: Serverless for Speed and Security",
    room: "pacificHall",
    start: "16:00",
    end: "16:30",
    speaker: "Mirembe Rebecca Peace",
  },
  {
    id: 20,
    title: "Closing Keynote",
    room: "pacificHall",
    start: "16:30",
    end: "17:30",
    speaker: "Ceaser Wisdom Favor",
  },
  {
    id: 21,
    title: "Announcements and Closing",
    room: "pacificHall",
    start: "17:30",
    end: "18:00",
  },
];

export const PYCON_DAY5_SCHEDULE = [
  {
    id: 1,
    title: "Breakfast and Expo time",
    room: ["pacificHall", "voltaRoom", "videoConferenceRoom"],
    start: "7:00",
    end: "10:00",
  },
  {
    id: 101,
    title: "Keynote",
    room: "pacificHall",
    start: "10:00",
    end: "11:00",
    speaker: "Robert Mutyaba",
  },
  {
    id: 2,
    title: "Python in Smart Contract development",
    room: "pacificHall",
    start: "11:00",
    end: "11:30",
    speaker: "Jovan Mwesigwa",
  },
  {
    id: 3,
    title: "Django Girls Workshop",
    room: "voltaRoom",
    start: "11:00",
    end: "13:00",
    speaker: "Ann Namuli, Dorothy Kabarozi and Eva Nanyonga",
    tag: "django-girls",
  },
  {
    id: 103,
    title: "Django Girls Workshop",
    room: "voltaRoom",
    start: "14:00",
    end: "16:30",
    speaker: "Ann Namuli, Dorothy Kabarozi and Eva Nanyonga",
    tag: "django-girls",
  },
  {
    id: 4,
    title: "PyLadies Kampala Anniversary Workshop",
    room: "videoConferenceRoom",
    start: "11:00",
    end: "13:00",
    speaker: "Deoborah Lanyero and Monica Iyabo",
    tag: "pyladies",
  },
  {
    id: 104,
    title: "PyLadies Kampala Anniversary Workshop",
    room: "videoConferenceRoom",
    start: "14:00",
    end: "16:30",
    speaker: "Deoborah Lanyero and Monica Iyabo",
    tag: "pyladies",
  },
  {
    id: 5,
    title: "Python For The Web?",
    room: "pacificHall",
    start: "11:30",
    end: "12:00",
    speaker: "Hussein Kizz",
  },
  {
    id: 6,
    title:
      "Two of Yourself😃: How to Create a Digital A.I Clone to Double Your output!",
    room: "pacificHall",
    start: "12:00",
    end: "12:30",
    speaker: "Ssemujju Sharif",
  },
  {
    id: 7,
    title:
      "Building the Future: Leveraging Tech Talent & AI for Sustainable Growth in Africa",
    room: "pacificHall",
    start: "12:30",
    end: "13:00",
    speaker: "Sodiq Akinjobi",
  },
  {
    id: 8,
    title: "Lunch Break",
    room: ["pacificHall", "voltaRoom", "videoConferenceRoom"],
    start: "13:00",
    end: "14:00",
    speaker: null,
  },
  {
    id: 9,
    title: "Build LLM-powered Web Apps with Django and Gemini API",
    room: "pacificHall",
    start: "14:00",
    end: "14:30",
    speaker: "Wesley Kambale",
  },
  {
    id: 10,
    title: "Learning Python by solving programming problems",
    room: "pacificHall",
    start: "14:30",
    end: "15:00",
    speaker: "Zain Shabbir",
  },
  {
    id: 11,
    title: "Applying Machine Learning in Software Engineering",
    room: "pacificHall",
    start: "15:00",
    end: "15:30",
    speaker: "John Pangas",
  },
  {
    id: 12,
    title: "NASA TOPS: Information Session",
    room: "pacificHall",
    start: "15:30",
    end: "16:00",
    speaker: "James Powell, Cameron Riddell, and Courtney Haun",
  },
  {
    id: 13,
    title:
      "Python for Financial Data Analysis: Predicting Market Trends and Optimizing Investments",
    room: "pacificHall",
    start: "16:00",
    end: "16:30",
    speaker: "Abraham Imani Bahati",
  },
  {
    id: 14,
    title: "Keynote",
    room: "pacificHall",
    start: "17:00",
    end: "18:00",
    speaker: "Carol Willing",
  },
  {
    id: 15,
    title: "PyCon Closing Opening Address",
    room: "pacificHall",
    start: "18:00",
    end: "19:00",
  },
];
