export const Tabs = [
  { id: 1, title: "Day 1 (9th October)" },
  { id: 2, title: "Day 2 (10th October)" },
  { id: 3, title: "Day 3 (11th October)" },
  { id: 4, title: "Day 4 (12th October)" },
  { id: 5, title: "Day 5 (13th October)" },
];

export const PYCON_DAY1_SCHEDULE = [
  {
    id: 1,
    title: "Breakfast and Expo time",
    room: [
      "innovationFloor",
      "voltaRoom",
      "pacificHall",
      "videoConferenceRoom",
    ],
    start: "7:00",
    end: "10:00",
    tag: "break",
  },
  {
    id: 2,
    title: "Welcome and PyCon Official Opening Address",
    room: "innovationFloor",
    start: "10:00",
    end: "11:00",
  },
  {
    id: 3,
    title: "Plenary Address from Government Official",
    room: "innovationFloor",
    start: "11:00",
    end: "12:00",
  },
  {
    id: 4,
    title: "Pulitzer Center Sponsor Talk",
    room: "pacificHall",
    start: "12:00",
    end: "13:00",
  },
  {
    id: 5,
    title: "Chaos Africa Sponsor Talk",
    room: "innovationFloor",
    start: "12:00",
    end: "13:00",
  },
  {
    id: 6,
    title: "Open Source Sprints",
    room: "videoConferenceRoom",
    start: "10:00",
    end: "13:00",
    tag: "opensource-sprints",
  },
  {
    id: 7,
    title: "Open Source Sprints",
    room: "videoConferenceRoom",
    start: "14:00",
    end: "17:00",
    tag: "opensource-sprints",
  },
  {
    id: 8,
    title: "Lunch Break",
    room: [
      "innovationFloor",
      "voltaRoom",
      "pacificHall",
      "videoConferenceRoom",
    ],
    start: "13:00",
    end: "14:00",
  },

  {
    id: 10,
    title: "Open Source Panel Session",
    room: "innovationFloor",
    start: "14:00",
    end: "15:00",
  },
  {
    id: 11,
    title: "Crane Cloud Workshop",
    room: "pacificHall",
    start: "15:00",
    end: "16:00",
  },
  {
    id: 12,
    title: "MTN MoMo Workshop",
    room: "innovationFloor",
    start: "15:00",
    end: "16:00",
  },
  {
    id: 13,
    title:
      "From Workshops to Masterminds: Building a thriving Python Community with the Python Ho User Group.",
    room: "voltaRoom",
    start: "15:00",
    end: "16:00",
    speaker: "Kafui Alordo",
  },
  {
    id: 14,
    title: "CEDAT Workshop",
    room: "pacificHall",
    start: "16:00",
    end: "17:00",
  },
  {
    id: 15,
    title: "Stanbic Workshop",
    room: "innovationFloor",
    start: "16:00",
    end: "17:00",
  },

  {
    id: 17,
    title: "Closing Keynote",
    room: "innovationFloor",
    start: "17:00",
    end: "18:00",
  },
  {
    id: 18,
    title: "Announcements and Closing",
    room: "innovationFloor",
    start: "18:00",
    end: "18:30",
  },
  {
    id: 18,
    title: "Welcome remarks and Introductions",
    room: "voltaRoom",
    start: "10:00",
    end: "11:00",
    speaker: "Deborah Lanyero",
    tag: "community-summit",
  },
  {
    id: 19,
    title: "Keynote Session",
    room: "voltaRoom",
    start: "11:00",
    end: "12:00",
    speaker: "Deborah Lanyero",
    tag: "community-summit",
  },
  {
    id: 20,
    title:
      "From Workshops to Masterminds: Building a thriving Python Community with the Python Ho User Group.",
    room: "voltaRoom",
    start: "12:00",
    end: "12:30",
    speaker: "Kafui Alordo",
    tag: "community-summit",
  },
  {
    id: 21,
    title:
      "Empowering Diverse Communities with Python: Insights from Mombasa, Kenya.",
    room: "voltaRoom",
    start: "12:30",
    end: "13:00",
    speaker: "Chris N. Achinga",
    tag: "community-summit",
  },
  {
    id: 22,
    title:
      "Harnessing Collective Intelligence: Developing and Utilizing Data Science Communities",
    room: "voltaRoom",
    start: "14:00",
    end: "14:30",
    speaker: "Bernice Omiunu",
    tag: "community-summit",
  },
  {
    id: 23,
    title: "OpenSource at Pykampala community",
    room: "voltaRoom",
    start: "14:30",
    end: "15:00",
    speaker: "Tobias Higenyi",
    tag: "community-summit",
  },
  {
    id: 24,
    title: "Discussion on Community way forward",
    room: "voltaRoom",
    start: "15:00",
    end: "16:00",
    speaker: "Deborah Lanyero",
    tag: "community-summit",
  },
  {
    id: 25,
    title: "Closing Remarks and End",
    room: "voltaRoom",
    start: "16:00",
    end: "16:30",
    tag: "community-summit",
  },
  {
    id: 26,
    title: "Microsoft Sponsor Talk",
    room: "pacificHall",
    start: "11:00",
    end: "12:00",
  },
  {
    id: 27,
    title: "Posit Workshop",
    room: "pacificHall",
    start: "14:00",
    end: "15:00",
  },
];

export const PYCON_DAY2_SCHEDULE = [
  {
    id: 1,
    title: "Breakfast and Expo time",
    room: [
      "innovationFloor",
      "voltaRoom",
      "pacificHall",
      "videoConferenceRoom",
    ],
    start: "7:00",
    end: "10:00",
  },
  {
    id: 2,
    title: "State of the Community Address",
    room: "innovationFloor",
    start: "10:00",
    end: "11:00",
  },
  {
    id: 3,
    title: "Opening Keynote",
    room: "innovationFloor",
    start: "11:00",
    end: "12:00",
  },

  {
    id: 5,
    title: "All Open Source Africa Workshop",
    room: "innovationFloor",
    start: "12:00",
    end: "13:00",
  },
  {
    id: 6,
    title: "Lunch Break",
    room: [
      "innovationFloor",
      "voltaRoom",
      "pacificHall",
      "videoConferenceRoom",
    ],
    start: "13:00",
    end: "14:00",
  },
  {
    id: 7,
    title: "Diversity and Inclusion Panel",
    room: "innovationFloor",
    start: "14:00",
    end: "15:00",
  },

  {
    id: 9,
    title: "FundiBots Workshop",
    room: "innovationFloor",
    start: "15:00",
    end: "16:00",
  },
  {
    id: 10,
    title: "Policy Workshop",
    room: "pacificHall",
    start: "16:00",
    end: "17:00",
  },
  {
    id: 11,
    title: "DataLadies Workshop",
    room: "innovationFloor",
    start: "16:00",
    end: "17:00",
  },
  {
    id: 12,
    title: "Career Panel",
    room: "innovationFloor",
    start: "17:00",
    end: "18:00",
  },
  {
    id: 13,
    title: "Announcements and Closing",
    room: "innovationFloor",
    start: "18:00",
    end: "18:30",
  },

  {
    id: 15,
    title: "Welcome Address",
    room: "voltaRoom",
    start: "9:00",
    end: "9:30",
    tag: "django-girls",
  },
  {
    id: 16,
    title: "Keynote",
    room: "voltaRoom",
    start: "9:30",
    end: "10:00",
    tag: "django-girls",
  },
  {
    id: 17,
    title: "Dive into Python",
    room: "voltaRoom",
    start: "10:00",
    end: "11:00",
    tag: "django-girls",
  },

  {
    id: 19,
    title: "Dive into Django",
    room: "voltaRoom",
    start: "11:00",
    end: "13:00",
    tag: "django-girls",
  },
  {
    id: 20,
    title: "Lunch Break",
    room: [
      "innovationFloor",
      "voltaRoom",
      "pacificHall",
      "videoConferenceRoom",
    ],
    start: "13:00",
    end: "14:00",
    tag: "django-girls",
  },
  {
    id: 21,
    title: "More Django and Deployment",
    room: "voltaRoom",
    start: "14:00",
    end: "16:45",
    tag: "django-girls",
  },
  {
    id: 22,
    title: "Break",
    room: "voltaRoom",
    start: "16:45",
    end: "17:00",
    tag: "django-girls",
  },
  {
    id: 23,
    title: "Fixing Bugs and AOB",
    room: "voltaRoom",
    start: "17:00",
    end: "17:30",
    tag: "django-girls",
  },
  {
    id: 24,
    title: "Wrap up and announcements and photoshoot",
    room: "voltaRoom",
    start: "17:30",
    end: "18:00",
    tag: "django-girls",
  },
  {
    id: 24,
    title: "PyData Workshops",
    room: "pacificHall",
    start: "10:00",
    end: "13:00",
    tag: "pydata",
  },
  {
    id: 24,
    title: "PyData Workshops",
    room: "pacificHall",
    start: "14:00",
    end: "16:00",
    tag: "pydata",
  },
];

export const PYCON_DAY3_SCHEDULE = [
  {
    id: 1,
    title: "Registration and Expo time",
    room: [
      "innovationFloor",
      "voltaRoom",
      "pacificHall",
      "videoConferenceRoom",
    ],
    start: "8:00",
    end: "9:00",
    speaker: null,
  },
  {
    id: 2,
    title: "Opening Keynote",
    room: "innovationFloor",
    start: "9:00",
    end: "10:00",
    speaker: null,
  },
  {
    id: 101,
    title: "Break tea",
    room: [
      "innovationFloor",
      "voltaRoom",
      "pacificHall",
      "videoConferenceRoom",
    ],
    start: "10:00",
    end: "11:00",
    speaker: null,
  },
  {
    id: 3,
    title:
      "Web: FastDjango: Conjuring Powerful APIs with the Sorcery of Django Ninja",
    room: "pacificHall",
    start: "11:00",
    end: "11:30",
    speaker: "Julius Boakye",
  },
  {
    id: 4,
    title: "Building SMART Recommendation Systems in Python (Using intellikit)",
    room: "innovationFloor",
    start: "11:00",
    end: "11:30",
    speaker: "Arthur Kakande",
  },
  {
    id: 5,
    title: "Serving TensorFlow Models with FastAPI",
    room: "voltaRoom",
    start: "11:00",
    end: "12:00",
    speaker: "Wesley Kambale",
  },
  {
    id: 6,
    title: "Full Stack Python Web Dev? Introducing Reflex",
    room: "pacificHall",
    start: "11:30",
    end: "12:00",
    speaker: "Ssali Jonathan Kiggundu",
  },
  {
    id: 7,
    title:
      "Core Principles: Exploring Asynchronous IO Patterns in Python: Strategies for Enhanced Performance and Scalability",
    room: "pacificHall",
    start: "12:00",
    end: "12:30",
    speaker: "Angufibo Lincoln",
  },
  {
    id: 8,
    title: "Explainable AI with Python",
    room: "innovationFloor",
    start: "12:00",
    end: "12:30",
    speaker: "Brayan Mwanyumba",
  },
  {
    id: 9,
    title:
      "Python with Kafka: Get started on modern stream processing with Python",
    room: "voltaRoom",
    start: "12:00",
    end: "13:00",
    speaker: "Mark Lubega",
  },
  {
    id: 10,
    title: "End-to-end testing with Selenium and Python",
    room: "pacificHall",
    start: "12:30",
    end: "13:00",
    speaker: "Victoria Mutai",
  },
  {
    id: 11,
    title: "Lunch Break",
    room: [
      "innovationFloor",
      "voltaRoom",
      "pacificHall",
      "videoConferenceRoom",
    ],
    start: "13:00",
    end: "14:00",
    speaker: null,
  },
  {
    id: 12,
    title: "Official Expo Hall Time",
    room: "innovationFloor",
    start: "14:00",
    end: "14:30",
    speaker: null,
  },
  {
    id: 13,
    title:
      "Dive into the world of Explainable AI (XAI) with Python, exploring how to make AI models transparent and understandable, fostering trust and ethical use in AI applications",
    room: "pacificHall",
    start: "14:30",
    end: "15:00",
    speaker: "Brayan Mwanyumba",
  },
  {
    id: 14,
    title: "Click It & Script It: Automating Your Desktop with PyAutoGUI",
    room: "innovationFloor",
    start: "14:30",
    end: "15:00",
    speaker: "Collins Mesue",
  },
  {
    id: 15,
    title: "Data to Dialogue: develop an end-to-end RAG application",
    room: "voltaRoom",
    start: "14:00",
    end: "15:00",
    speaker: "Bethany Jepchumba",
  },
  {
    id: 16,
    title: "Pulitzer Center Sponsor Workshop",
    room: "videoConferenceRoom",
    start: "14:30",
    end: "15:00",
    speaker: null,
  },
  {
    id: 17,
    title: "Efficient Integration Testing using TestContainers",
    room: "pacificHall",
    start: "15:00",
    end: "15:30",
    speaker: "Sameer Shukla",
  },
  {
    id: 18,
    title: "Revolutioned. Whats New in Python 3.10",
    room: "pacificHall",
    start: "15:30",
    end: "16:00",
    speaker: "Allan Kiche",
  },
  {
    id: 19,
    title:
      "Leveraging Kafka Streams: Real-time Logging and Monitoring for Django Application",
    room: "innovationFloor",
    start: "15:30",
    end: "16:00",
    speaker: "Okot Daniel",
  },
  {
    id: 20,
    title: "Introduction to Computer Vision in Python",
    room: "voltaRoom",
    start: "15:00",
    end: "16:00",
    speaker: "Baker Sentamu",
  },
  {
    id: 21,
    title: "Beginner's Guide to Data Orchestration with Apache Airflow",
    room: "pacificHall",
    start: "16:00",
    end: "16:30",
    speaker: "Okumu Justine",
  },
  {
    id: 22,
    title: "Closing Keynote",
    room: "innovationFloor",
    start: "16:30",
    end: "17:30",
    speaker: null,
  },
  {
    id: 23,
    title: "Announcements and Closing",
    room: "innovationFloor",
    start: "17:30",
    end: "18:00",
    speaker: null,
  },
];

export const PYCON_DAY4_SCHEDULE = [
  {
    id: 1,
    title: "Registration and Expo time",
    room: [
      "innovationFloor",
      "voltaRoom",
      "pacificHall",
      "videoConferenceRoom",
    ],
    start: "8:00",
    end: "9:00",
    speaker: null,
  },
  {
    id: 2,
    title: "Opening Keynote",
    room: "innovationFloor",
    start: "9:00",
    end: "10:00",
    speaker: null,
  },
  {
    id: 101,
    title: "Break tea",
    room: [
      "innovationFloor",
      "voltaRoom",
      "pacificHall",
      "videoConferenceRoom",
    ],
    start: "10:00",
    end: "11:00",
    speaker: null,
  },
  {
    id: 3,
    title: "Deploying Python on Serverless Infrastructure for Free",
    room: "pacificHall",
    start: "11:00",
    end: "11:30",
    speaker: "Kayondo Edward",
  },
  {
    id: 4,
    title: "Build LLM-powered Web Apps with Django and Gemini API",
    room: "innovationFloor",
    start: "11:00",
    end: "11:30",
    speaker: "Wesley Kambale",
  },
  {
    id: 5,
    title: "Guide to Test-Driven Development using PyTest",
    room: "voltaRoom",
    start: "11:00",
    end: "12:00",
    speaker: "Doki Golder Sylivia",
  },
  {
    id: 6,
    title:
      "Exploring Conversational AI: Crafting AI-Powered Django Apps with Gemini",
    room: "pacificHall",
    start: "11:30",
    end: "12:00",
    speaker: "Hassan Bahati",
  },
  {
    id: 7,
    title:
      "From Syntax to Solutions: Mastering Technical Writing for Developers",
    room: "pacificHall",
    start: "12:00",
    end: "12:30",
    speaker: "Fanny Nyayic",
  },
  {
    id: 8,
    title: "API 101 API fundamentals",
    room: "innovationFloor",
    start: "12:00",
    end: "12:30",
    speaker: "Felix Jumason",
  },
  {
    id: 9,
    title:
      "Integrating Python and Google Gemini: Crafting Cutting-Edge AI Applications",
    room: "voltaRoom",
    start: "12:00",
    end: "13:00",
    speaker: "Julius Boakye",
  },
  {
    id: 10,
    title: "Python in Web3: Libraries, Techniques, and Local Dev Challenges",
    room: "pacificHall",
    start: "12:30",
    end: "13:00",
    speaker: "Oliseh Genesis",
  },
  {
    id: 11,
    title: "Lunch Break",
    room: [
      "innovationFloor",
      "voltaRoom",
      "pacificHall",
      "videoConferenceRoom",
    ],
    start: "13:00",
    end: "14:00",
    speaker: null,
  },
  {
    id: 12,
    title: "Official Expo Hall Time",
    room: "innovationFloor",
    start: "14:00",
    end: "14:30",
    speaker: null,
  },
  {
    id: 13,
    title: "Python for C2 (Command and Control) Operations",
    room: "pacificHall",
    start: "14:00",
    end: "15:00",
    speaker: "Salim Abdella",
  },
  {
    id: 14,
    title: "Crafting Ubiquity: A Model's Odyssey",
    room: "innovationFloor",
    start: "14:30",
    end: "15:00",
    speaker: "Kayongo Johnson Brian",
  },
  {
    id: 15,
    title: "Behind the scenes of an Ads Prediction System",
    room: "voltaRoom",
    start: "14:00",
    end: "15:00",
    speaker: "Bunmi Akinremi",
  },
  {
    id: 16,
    title: "Building and Consuming APIs with Python",
    room: "pacificHall",
    start: "15:00",
    end: "15:30",
    speaker: "Felix Jumason",
  },
  {
    id: 17,
    title: "Django Rest Framework with J2J architecture",
    room: "pacificHall",
    start: "15:30",
    end: "16:00",
    speaker: "Tumusiime Ezra",
  },
  {
    id: 18,
    title: "Train & Debug A model with Responsible AI Dashboard",
    room: "innovationFloor",
    start: "15:30",
    end: "16:00",
    speaker: "Anthony Byansi",
  },
  {
    id: 19,
    title: "GitHub Sponsor Student Workshop",
    room: "voltaRoom",
    start: "15:00",
    end: "16:00",
    speaker: "Allan Kiche and Brayan Kai Mwanyumba",
  },
  {
    id: 20,
    title: "Unlock Python's Potential: Serverless for Speed and Security",
    room: "pacificHall",
    start: "16:00",
    end: "17:00",
    speaker: "Mirembe Rebecca Peace",
  },
  {
    id: 21,
    title: "Closing Keynote",
    room: "innovationFloor",
    start: "16:30",
    end: "17:30",
    speaker: null,
  },
  {
    id: 22,
    title: "Announcements and Closing",
    room: "innovationFloor",
    start: "17:30",
    end: "18:00",
    speaker: null,
  },
];

export const PYCON_DAY5_SCHEDULE = [
  {
    id: 1,
    title: "Registration and Expo time",
    room: [
      "innovationFloor",
      "voltaRoom",
      "pacificHall",
      "videoConferenceRoom",
    ],
    start: "8:00",
    end: "9:00",
    speaker: null,
  },
  {
    id: 2,
    title: "Opening Keynote",
    room: "innovationFloor",
    start: "9:00",
    end: "10:00",
    speaker: null,
  },
  {
    id: 101,
    title: "Break tea",
    room: [
      "innovationFloor",
      "voltaRoom",
      "pacificHall",
      "videoConferenceRoom",
    ],
    start: "10:00",
    end: "11:00",
    speaker: null,
  },
  {
    id: 3,
    title: "Python in Smart Contract development",
    room: "pacificHall",
    start: "11:00",
    end: "11:30",
    speaker: "Jovan Mwesigwa",
  },
  // {
  //   id: 4,
  //   title: "Django Girls Workshop",
  //   room: "innovationFloor",
  //   start: "11:00",
  //   end: "11:30",
  //   speaker: "Ann Namuli, Dorothy Kabarozi and Eva Nanyonga",
  // },
  {
    id: 5,
    title: "Welcome remarks and Introductions",
    room: "voltaRoom",
    start: "10:00",
    end: "11:00",
    speaker: "Deoborah Lanyero and Monica Iyabo",
    tag: "pyladies",
  },
  {
    id: 6,
    title: "Python For The Web?",
    room: "pacificHall",
    start: "11:30",
    end: "12:00",
    speaker: "Hussein Kizz",
  },
  {
    id: 7,
    title:
      "Two of Yourself😃: How to Create a Digital A.I Clone to Double Your output!",
    room: "pacificHall",
    start: "12:00",
    end: "12:30",
    speaker: "Ssemujju Sharif",
  },
  {
    id: 8,
    title:
      "Building the Future: Leveraging Tech Talent & AI for Sustainable Growth in Africa",
    room: "pacificHall",
    start: "12:30",
    end: "13:00",
    speaker: "Sodiq Akinjobi",
  },
  {
    id: 9,
    title: "Lunch Break",
    room: [
      "innovationFloor",
      "voltaRoom",
      "pacificHall",
      "videoConferenceRoom",
    ],
    start: "13:00",
    end: "14:00",
    speaker: null,
  },
  {
    id: 10,
    title: "Using the Power of AI in web applications",
    room: "pacificHall",
    start: "14:00",
    end: "14:30",
    speaker: "Ariyo Ahumuza",
  },
  {
    id: 11,
    title: "Learning Python by solving programming problems",
    room: "pacificHall",
    start: "14:30",
    end: "15:00",
    speaker: "Zain Shabbir",
  },
  {
    id: 12,
    title: "Analytics using Natural Language and LLMs",
    room: "pacificHall",
    start: "15:00",
    end: "15:30",
    speaker: "Josh Ndemenge",
  },
  {
    id: 13,
    title: "Inside multimodal models",
    room: "pacificHall",
    start: "15:30",
    end: "16:00",
    speaker: "Bethany Jepchumba",
  },
  {
    id: 14,
    title:
      "Python for Financial Data Analysis: Predicting Market Trends and Optimizing Investments",
    room: "pacificHall",
    start: "16:00",
    end: "16:30",
    speaker: "Abraham Imani Bahati",
  },
  {
    id: 15,
    title: "Closing Keynote",
    room: "innovationFloor",
    start: "16:30",
    end: "17:30",
    speaker: null,
  },
  {
    id: 16,
    title: "Announcements and Closing",
    room: "innovationFloor",
    start: "17:30",
    end: "18:00",
    speaker: null,
  },
  {
    id: 17,
    title: "Keynote Session",
    room: "voltaRoom",
    start: "11:00",
    end: "12:00",
    speaker: "Deoborah Lanyero and Monica Iyabo",
    tag: "pyladies",
  },
  {
    id: 18,
    title:
      "Women in STEM! Championing Diversity and Inclusion in the Tech Industry!",
    room: "voltaRoom",
    start: "12:00",
    end: "12:30",
    speaker: "Deoborah Lanyero and Monica Iyabo",
    tag: "pyladies",
  },
  {
    id: 19,
    title: "Teach me through Python",
    room: "voltaRoom",
    start: "12:30",
    end: "13:00",
    speaker: "Deoborah Lanyero and Monica Iyabo",
    tag: "pyladies",
  },
  {
    id: 20,
    title: "Women Tech Makers in Kampala: Get Involved",
    room: "voltaRoom",
    start: "14:30",
    end: "15:00",
    speaker: "Deoborah Lanyero and Monica Iyabo",
    tag: "pyladies",
  },
  {
    id: 21,
    title:
      "Harnessing Collective Intelligence : Developing and Utilizing Data Science Communities",
    room: "voltaRoom",
    start: "15:00",
    end: "15:30",
    speaker: "Deoborah Lanyero and Monica Iyabo",
    tag: "pyladies",
  },
  {
    id: 22,
    title: "Advanced Django as a Professional",
    room: "voltaRoom",
    start: "15:30",
    end: "16:00",
    speaker: "Deoborah Lanyero and Monica Iyabo",
    tag: "pyladies",
  },
  {
    id: 23,
    title: "Closing Remarks and End",
    room: "voltaRoom",
    start: "16:00",
    end: "16:30",
    speaker: "Deoborah Lanyero and Monica Iyabo",
    tag: "pyladies",
  },
];
